### ISSUE TITLE
Can't get P3 working after migration from Pharo 8 to 9

### ISSUE THREAD

**Issue by riVDM** [svenvc/P3#27]
Hi,
I had to migrate from Pharo 8 to 9 and re-installed P3 with the following scripts (the same i had used to install P3 in Pharo 8)

_Metacello new
   baseline: 'P3';
   repository: 'github://svenvc/P3';
   load._

and

_Metacello new
   baseline: 'P3';
   repository: 'github://svenvc/P3';
   load: 'glorp'._

I also re-installed DBXTalk/Glorp/main
and "do-it" : PharoDatabaseAccessor DefaultDriver: P3DatabaseDriver.

Before that i installed Spec2.

Then i tried to run this script
(P3Client new url: 'psql://Richard:lulosa.2MA@localhost:5432/Glazux') in: [ :client |
   [ client query: 'SELECT * FROM ingredients' ] ensure: [ client close ] ].

but got this error:
![P3-Pbm](https://user-images.githubusercontent.com/67067876/85925706-88ee1480-b89a-11ea-8dbb-8c3e76d74b48.png)

I probably forgot to do something but i don't remember what. Do i need to install a MetaRepoForPharo? But which version?
Thanks for help
Richard
(btw: the same script runs ok in Pharo 8)

**Comment by svenvc** [comment]
Yes I know. 

If you implement #digitAt: on Integer as an alias to #byteAt: it will probably work.

A library like P3 (or any of my libraries, like Zinc) cannot be compatible with Pharo 7, 8 and 9 at the same time because of this change.

I requested a backport of a small change to Pharo 7 to get over this, but it did not yet get accepted/released.

**Comment by riVDM** [comment]
I did what you suggest (i hope i did it correctly, at the right place) and it works now! Thank you!
Richard
![image](https://user-images.githubusercontent.com/67067876/85941811-84227280-b925-11ea-8cb3-b72c6087130f.png)
